// AUTH ACTION TYPES
export const AUTH_ACTION_START = 'AUTH_ACTION_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// RECORDING ACTION TYPES
export const RECORDING_ACTION_START = 'RECORDING_ACTION_START';
export const GET_ALL_RECORDINGS_SUCCESS = 'GET_ALL_RECORDINGS_SUCCESS';
export const GET_ALL_RECORDINGS_FAILED = 'GET_ALL_RECORDINGS_FAILED';
